#!/usr/bin/env python3

import argparse
import base64
import getpass
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import boto3


def decode_payload(token: str) -> dict[str, Any]:
    parts = token.split(".")
    if len(parts) != 3:
        raise ValueError("The access token is not a JWT.")

    payload = parts[1]
    payload += "=" * (-len(payload) % 4)
    return json.loads(
        base64.urlsafe_b64decode(payload).decode("utf-8")
    )


def iso_from_epoch(value: Any) -> str:
    return datetime.fromtimestamp(
        int(value),
        tz=timezone.utc,
    ).isoformat()


def authenticate(
    client: Any,
    client_id: str,
    username: str,
    password: str,
) -> dict[str, Any]:
    response = client.initiate_auth(
        ClientId=client_id,
        AuthFlow="USER_PASSWORD_AUTH",
        AuthParameters={
            "USERNAME": username,
            "PASSWORD": password,
        },
    )

    while response.get("ChallengeName"):
        challenge = response["ChallengeName"]

        if challenge == "SOFTWARE_TOKEN_MFA":
            code = input(
                "Enter the current authenticator code: "
            ).strip()
            response = client.respond_to_auth_challenge(
                ClientId=client_id,
                ChallengeName=challenge,
                Session=response["Session"],
                ChallengeResponses={
                    "USERNAME": username,
                    "SOFTWARE_TOKEN_MFA_CODE": code,
                },
            )
            continue

        if challenge == "MFA_SETUP":
            association = client.associate_software_token(
                Session=response["Session"]
            )
            secret = association["SecretCode"]

            print("\nTOTP setup is required.")
            print(
                "Add this secret to an authenticator application:"
            )
            print(secret)
            code = input(
                "Enter the code generated by the authenticator: "
            ).strip()

            verification = client.verify_software_token(
                Session=association["Session"],
                UserCode=code,
                FriendlyDeviceName="Security Lab",
            )

            if verification.get("Status") != "SUCCESS":
                raise RuntimeError(
                    "Cognito did not accept the TOTP setup."
                )

            response = client.respond_to_auth_challenge(
                ClientId=client_id,
                ChallengeName="MFA_SETUP",
                Session=verification["Session"],
                ChallengeResponses={
                    "USERNAME": username,
                },
            )
            continue

        if challenge == "NEW_PASSWORD_REQUIRED":
            new_password = getpass.getpass(
                "Enter a new permanent password: "
            )
            response = client.respond_to_auth_challenge(
                ClientId=client_id,
                ChallengeName=challenge,
                Session=response["Session"],
                ChallengeResponses={
                    "USERNAME": username,
                    "NEW_PASSWORD": new_password,
                },
            )
            continue

        raise RuntimeError(
            f"Unsupported Cognito challenge: {challenge}"
        )

    authentication_result = response.get(
        "AuthenticationResult"
    )
    if not authentication_result:
        raise RuntimeError(
            "Cognito did not return an authentication result."
        )

    return authentication_result


def track_token(
    table_name: str,
    region: str,
    claims: dict[str, Any],
) -> None:
    token_id = claims.get("jti")
    if not token_id:
        raise ValueError(
            "The access token does not contain a jti claim."
        )

    issued_at = iso_from_epoch(claims["iat"])
    expires_at = iso_from_epoch(claims["exp"])

    item = {
        "token_id": str(token_id),
        "token_id_type": "cognito_access_token_jti",
        "origin_jti": str(
            claims.get("origin_jti", "not_present")
        ),
        "username": str(
            claims.get("username", "unknown")
        ),
        "issued_at": issued_at,
        "issued_at_epoch": int(claims["iat"]),
        "expires_at": expires_at,
        "expires_at_epoch": int(claims["exp"]),
        "used": False,
        "alerted": False,
        "token_status": "ISSUED",
        "groups": claims.get("cognito:groups", []),
        "scope": str(claims.get("scope", "")),
        "source_ip": "not_collected",
        "device": "not_collected",
        "geography": "not_collected",
        "mfa_context": "not_collected",
    }

    table = boto3.resource(
        "dynamodb",
        region_name=region,
    ).Table(table_name)

    table.put_item(
        Item=item,
        ConditionExpression=(
            "attribute_not_exists(token_id)"
        ),
    )


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Authenticate a Cognito lab user, register the "
            "access-token jti, and save the token to a local file."
        )
    )
    parser.add_argument(
        "--region",
        default=os.environ.get("AWS_REGION", "eu-central-1"),
    )
    parser.add_argument(
        "--client-id",
        default=os.environ.get("COGNITO_CLIENT_ID"),
    )
    parser.add_argument(
        "--table",
        default=os.environ.get("TOKEN_TRACKING_TABLE"),
    )
    parser.add_argument(
        "--username",
        required=True,
    )
    parser.add_argument(
        "--token-file",
        default=os.environ.get(
            "TOKEN_FILE",
            "/tmp/security-lab-access-token",
        ),
    )
    arguments = parser.parse_args()

    if not arguments.client_id:
        parser.error(
            "--client-id or COGNITO_CLIENT_ID is required"
        )
    if not arguments.table:
        parser.error(
            "--table or TOKEN_TRACKING_TABLE is required"
        )

    return arguments


def main() -> None:
    arguments = parse_arguments()
    password = getpass.getpass("Password: ")

    client = boto3.client(
        "cognito-idp",
        region_name=arguments.region,
    )
    result = authenticate(
        client=client,
        client_id=arguments.client_id,
        username=arguments.username,
        password=password,
    )

    access_token = result["AccessToken"]
    claims = decode_payload(access_token)
    track_token(
        table_name=arguments.table,
        region=arguments.region,
        claims=claims,
    )

    token_path = Path(arguments.token_file)
    token_path.write_text(access_token, encoding="utf-8")
    token_path.chmod(0o600)

    summary = {
        "username": claims.get("username"),
        "groups": claims.get("cognito:groups", []),
        "scope": claims.get("scope", ""),
        "jti": claims.get("jti"),
        "issued_at": iso_from_epoch(claims["iat"]),
        "expires_at": iso_from_epoch(claims["exp"]),
        "tracking_table": arguments.table,
        "token_file": str(token_path),
    }

    print("\nAuthentication and token registration succeeded.")
    print(json.dumps(summary, indent=2))
    print(
        "\nThe raw token was written with local permissions 0600. "
        "It was not printed."
    )


if __name__ == "__main__":
    main()
